server:
  port: 8761
  servlet:
    context-path: /myboot

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
  thymeleaf: 
    prefix: classpath:/templates/